version: '3.8'
services:
  node_application:
    container_name: my-express-app-container
    #build: ./Dockerfile
    build: .
    volumes:
      - ./src:/app/src:ro
    ports:
      - "4000:4000"
    # environment:
    #   - NODE_ENV=development
    #   - DB_NAME=TEST
    #   - PORT=4000
    env_file:
      - ./.env